/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2023-06-06 05:30:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class b_005floading_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"refresh\" content=\"2.9;url=board/list\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"resources/img/mlogo.svg\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>MATFLIX</title>\r\n");
      out.write("     <!-- [if lt IE9]>\r\n");
      out.write("        <script src=\"resources/b_loading/js/html5shiv.js\"></script>\r\n");
      out.write("    <![endif] -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/b_loading/css/bs.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("        <!-- <h1>COMMUNITY</h1> -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"resources/b_loading/js/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/b_loading/js/jquery.backstretch.min.js\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("   /*\r\n");
      out.write("        $(function(){\r\n");
      out.write("            $.backstretch([\r\n");
      out.write("      \"resources/bloading/images/1.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/2.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/3.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/4.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/5.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/6.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/7.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/8.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/9.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/10.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/11.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/12.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/13.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/14.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/15.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/16.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/17.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/18.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/19.jpg\"\r\n");
      out.write("    , \"resources/bloading/images/20.jpg\"\r\n");
      out.write("  ], {duration: 10, fade: 100});\r\n");
      out.write("        });\r\n");
      out.write("*/\r\n");
      out.write("        $(function(){\r\n");
      out.write("            $.backstretch([\r\n");
      out.write("\r\n");
      out.write("     \"resources/b_loading/images/2.jpg\"\r\n");
      out.write("    , \"resources/b_loading/images/4.jpg\"\r\n");
      out.write("    , \"resources/b_loading/images/6.jpg\"\r\n");
      out.write("    , \"resources/b_loading/images/8.jpg\"\r\n");
      out.write("    , \"resources/b_loading/images/10.jpg\"\r\n");
      out.write("    , \"resources/b_loading/images/12.jpg\"\r\n");
      out.write("    , \"resources/b_loading/images/14.jpg\"\r\n");
      out.write("    , \"resources/b_loading/images/16.jpg\"\r\n");
      out.write("    , \"resources/b_loading/images/18.jpg\"\r\n");
      out.write("    , \"resources/b_loading/images/20.jpg\"\r\n");
      out.write("  ], {duration: 20, fade: 250});\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
