/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2023-06-15 11:10:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>MATFLIX</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/popup/js/jquery.js\"></script>\r\n");
      out.write("<script src=\"resources/popup/js/jquery.cookie.js\"></script>\r\n");
      out.write("<!-- https://cdnjs.com/libraries/jquery-cookie -->\r\n");
      out.write("<script>\r\n");
      out.write("\t// jquery-cookie 플러그인을 사용하면 간편하게 쿠키(cookie)를 생성하고\r\n");
      out.write("\t// 쿠키 만료일을 설정할 수 있습니다. 쿠키란 '사이트를 방문한 사용자의\r\n");
      out.write("\t// 소량(4kb이하) 브라우저 정보를 저장할 수 있는 공간'을 말합니다.\r\n");
      out.write("\t// 쿠키는 하나의 도메인당 최대 20개를 생성할 수 있고,\r\n");
      out.write("\t// 최대 4kb까지 저장할 수 있습니다.\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t// 쿠키(\"popup\")의 값이 \"none\"이면 id값이 \"notice_wrap\" 인 요소를 숨깁니다.\r\n");
      out.write("\t\tif ($.cookie(\"popup\") == \"none\") {\r\n");
      out.write("\t\t\t$(\"#notice_wrap\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// class값이 \"closeBtn\"인 요소를 클릭하면 체크박스의 체크 유무에 따라 쿠키를 생성하여 3일간만 저장합니다.\r\n");
      out.write("\t\tvar $expiresChk = $(\"#expiresChk\");\r\n");
      out.write("\t\t$(\".closeBtn\").on(\"click\", closePop);\r\n");
      out.write("\t\tfunction closePop() {\r\n");
      out.write("\t\t\tif ($expiresChk.is(\":checked\")) {\r\n");
      out.write("\t\t\t\t$.cookie(\"popup\", \"none\", {\r\n");
      out.write("\t\t\t\t\texpires : 3,\r\n");
      out.write("\t\t\t\t\tpath : \"/\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#notice_wrap\").fadeOut(\"fast\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/main/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/main/css/mystyle.css\">\r\n");
      out.write("<script src=\"resources/main/javascript/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("<script src=\"resources/main/javascript/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"resources/img/mlogo.svg\">\r\n");
      out.write("\r\n");
      out.write("<!-- 결제 스크립트 시작 -->\r\n");
      out.write("<!-- https://portone.gitbook.io/docs/sdk/javascript-sdk-old -->\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\" ></script>\r\n");
      out.write("<!-- iamport.payment.js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.2.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function fn_buy1() {\r\n");
      out.write("\tvar IMP = window.IMP;\r\n");
      out.write("\t<!-- https://github.com/iamport/iamport-manual/blob/master/인증결제/README.md#pc-mobile -->\r\n");
      out.write("\tIMP.init('imp08681661'); //portone 대신 자신의 \"가맹점 식별코드\"를 사용하시면 됩니다\r\n");
      out.write("\t// IMP.request_pay(param, callback) 결제창 호출\r\n");
      out.write("\tIMP.request_pay({\r\n");
      out.write("\t\tpg: 'html5_inicis',\r\n");
      out.write("\t\tpay_method: 'card',\r\n");
      out.write("\t\tmerchant_uid : 'merchant_' + new Date().getTime(),\r\n");
      out.write("\t\tname : '결제테스트',\r\n");
      out.write("\t\tamount : 109000,\r\n");
      out.write("\t\tbuyer_email : 'romikiju1@gmail.com',\r\n");
      out.write("\t\tbuyer_name : '장나라',\r\n");
      out.write("\t\tbuyer_tel : '010-1234-5678',\r\n");
      out.write("\t\tbuyer_addr : '서울특별시 강남구 삼성동',\r\n");
      out.write("\t\tbuyer_postcode : '123-456',\r\n");
      out.write("\t\tm_redirect_url : '/paymentDone.do'\r\n");
      out.write("\t}, function(rsp) {  // callback\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif ( rsp.success ) {\r\n");
      out.write("\t\t\tvar paymentInfo = {\r\n");
      out.write("\t\t\t\timp_uid : rsp.imp_uid,\r\n");
      out.write("\t\t\t\tmerchant_uid : rsp.merchant_uid,\r\n");
      out.write("\t\t\t\tpaid_amount : rsp.paid_amount,\r\n");
      out.write("\t\t\t\tapply_num : rsp.apply_num,\r\n");
      out.write("\t\t\t\tpaid_at : new Date()\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/paymentProcess.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t\tdata : JSON.stringify(paymentInfo),\r\n");
      out.write("\t\t\tsuccess:function(data, textStatus){\r\n");
      out.write("\t\t\t\tconsole.log(paymentInfo);\r\n");
      out.write("\t\t\t\tlocation.href = \"/paymentDone.do\";\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"결제 실패 : \" + rsp.error_msg)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_buy2() {\r\n");
      out.write("\tvar IMP = window.IMP;\r\n");
      out.write("\t<!-- https://github.com/iamport/iamport-manual/blob/master/인증결제/README.md#pc-mobile -->\r\n");
      out.write("\tIMP.init('imp08681661'); //portone 대신 자신의 \"가맹점 식별코드\"를 사용하시면 됩니다\r\n");
      out.write("\t// IMP.request_pay(param, callback) 결제창 호출\r\n");
      out.write("\tIMP.request_pay({\r\n");
      out.write("\t\tpg: 'html5_inicis',\r\n");
      out.write("\t\tpay_method: 'card',\r\n");
      out.write("\t\tmerchant_uid : 'merchant_' + new Date().getTime(),\r\n");
      out.write("\t\tname : '결제테스트',\r\n");
      out.write("\t\tamount : 159000,\r\n");
      out.write("\t\tbuyer_email : 'romikiju1@gmail.com',\r\n");
      out.write("\t\tbuyer_name : '장나라',\r\n");
      out.write("\t\tbuyer_tel : '010-1234-5678',\r\n");
      out.write("\t\tbuyer_addr : '서울특별시 강남구 삼성동',\r\n");
      out.write("\t\tbuyer_postcode : '123-456',\r\n");
      out.write("\t\tm_redirect_url : '/paymentDone.do'\r\n");
      out.write("\t}, function(rsp) {  // callback\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif ( rsp.success ) {\r\n");
      out.write("\t\t\tvar paymentInfo = {\r\n");
      out.write("\t\t\t\timp_uid : rsp.imp_uid,\r\n");
      out.write("\t\t\t\tmerchant_uid : rsp.merchant_uid,\r\n");
      out.write("\t\t\t\tpaid_amount : rsp.paid_amount,\r\n");
      out.write("\t\t\t\tapply_num : rsp.apply_num,\r\n");
      out.write("\t\t\t\tpaid_at : new Date()\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/paymentProcess.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t\tdata : JSON.stringify(paymentInfo),\r\n");
      out.write("\t\t\tsuccess:function(data, textStatus){\r\n");
      out.write("\t\t\t\tconsole.log(paymentInfo);\r\n");
      out.write("\t\t\t\tlocation.href = \"/paymentDone.do\";\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"결제 실패 : \" + rsp.error_msg)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_buy3() {\r\n");
      out.write("\tvar IMP = window.IMP;\r\n");
      out.write("\t<!-- https://github.com/iamport/iamport-manual/blob/master/인증결제/README.md#pc-mobile -->\r\n");
      out.write("\tIMP.init('imp08681661'); //portone 대신 자신의 \"가맹점 식별코드\"를 사용하시면 됩니다\r\n");
      out.write("\t// IMP.request_pay(param, callback) 결제창 호출\r\n");
      out.write("\tIMP.request_pay({\r\n");
      out.write("\t\tpg: 'html5_inicis',\r\n");
      out.write("\t\tpay_method: 'card',\r\n");
      out.write("\t\tmerchant_uid : 'merchant_' + new Date().getTime(),\r\n");
      out.write("\t\tname : '결제테스트',\r\n");
      out.write("\t\tamount : 199000,\r\n");
      out.write("\t\tbuyer_email : 'romikiju1@gmail.com',\r\n");
      out.write("\t\tbuyer_name : '장나라',\r\n");
      out.write("\t\tbuyer_tel : '010-1234-5678',\r\n");
      out.write("\t\tbuyer_addr : '서울특별시 강남구 삼성동',\r\n");
      out.write("\t\tbuyer_postcode : '123-456',\r\n");
      out.write("\t\tm_redirect_url : '/paymentDone.do'\r\n");
      out.write("\t}, function(rsp) {  // callback\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif ( rsp.success ) {\r\n");
      out.write("\t\t\tvar paymentInfo = {\r\n");
      out.write("\t\t\t\timp_uid : rsp.imp_uid,\r\n");
      out.write("\t\t\t\tmerchant_uid : rsp.merchant_uid,\r\n");
      out.write("\t\t\t\tpaid_amount : rsp.paid_amount,\r\n");
      out.write("\t\t\t\tapply_num : rsp.apply_num,\r\n");
      out.write("\t\t\t\tpaid_at : new Date()\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/paymentProcess.do\",\r\n");
      out.write("\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t\tdata : JSON.stringify(paymentInfo),\r\n");
      out.write("\t\t\tsuccess:function(data, textStatus){\r\n");
      out.write("\t\t\t\tconsole.log(paymentInfo);\r\n");
      out.write("\t\t\t\tlocation.href = \"/paymentDone.do\";\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"결제 실패 : \" + rsp.error_msg)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Stylesheets -->\r\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700,400italic,300italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/assets/css/docs.theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Owl Stylesheets -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/assets/owlcarousel/assets/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/assets/owlcarousel/assets/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons -->\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"resources/assets/ico/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"resources/assets/ico/favicon.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Yeah i know js should not be in header. Its required for demos.-->\r\n");
      out.write("\r\n");
      out.write("    <!-- javascript -->\r\n");
      out.write("    <script src=\"resources/assets/vendors/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/assets/owlcarousel/owl.carousel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"top\"></div>\r\n");
      out.write("\t<!-- sticky-top 적용 : https://getbootstrap.com/docs/4.0/utilities/position/ -->\r\n");
      out.write("\t<div class=\"mybox sticky-top\">\r\n");
      out.write("\t\t<!-- 네비게이션 바 navbar-example2 활용 : https://getbootstrap.com/docs/4.0/components/scrollspy/#one -->\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light container\">\r\n");
      out.write("\t\t\t<!-- 로고 작성 -->\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" id=\"logo3\" href=\"\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"resources/main/images/mlogo.png\" alt=\"\" style=\"width:70px;\">\r\n");
      out.write("\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<!-- https://getbootstrap.com/docs/4.0/components/navbar/ -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/profile.jsp\">Matflix</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#first\">Restaurants</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#second\">Popularity</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#third\">Subscribe</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> Community </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/b_loading.jsp\">자유 게시판</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"/board2/list\">공지사항 게시판</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"/board/list\">상담 게시판</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"/board/list\">문의/Q&A 게시판</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"/board/list\">커뮤니티 게시판</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"/board/list\">상품 홍보/이벤트 게시판</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> Membership </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/customLogin\">Log in</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"/membership.jsp\">Sign up</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"/mypage.jsp\">My Page</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrapper\" data-spy=\"scroll\" data-target=\"#navbar-example2\"\r\n");
      out.write("\t\tdata-offset=\"0\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div class=\"ontop\">\r\n");
      out.write("\t\t\t\t<!-- h1>lorem2 -->\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/main/images/matlogos.svg\" alt=\"\">\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<!-- h4>lorem10 -->\r\n");
      out.write("\t\t\t\t<h5>The first famous restaurant OTT service</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 서브 텍스트 내용 작성 -->\r\n");
      out.write("\t\t<!-- https://getbootstrap.com/docs/4.0/layout/grid/ -->\r\n");
      out.write("\t\t<div class=\"section col col-lg-12\" id=\"first\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"large-12 columns\">\r\n");
      out.write("\t\t<h1 class=\"guro\">Franchise in Guro</h1>\r\n");
      out.write("          <div class=\"owl-carousel owl-theme\">\r\n");
      out.write("          \r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("             <img src=\"resources/main/images/mat-1.jpg\" style=\"width:300px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/mat-2.jpg\"><img src=\"resources/main/images/mat-2.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/mat-3.jpg\"><img src=\"resources/main/images/mat-3.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/mat-4.jpg\"><img src=\"resources/main/images/mat-4.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/mat-5.jpg\"><img src=\"resources/main/images/mat-5.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/mat-8.jpg\"><img src=\"resources/main/images/mat-8.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/mat-9.jpg\"><img src=\"resources/main/images/mat-9.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/mat-10.jpg\"><img src=\"resources/main/images/mat-10.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal1\">\r\n");
      out.write("         <button>&times;</button>\r\n");
      out.write("         <div class=\"modalBox1\">\r\n");
      out.write("         <img src=\"resources/main/images/mat-1.jpg\" style=\"width:600px;\">\r\n");
      out.write("         <p></p>\r\n");
      out.write("      </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          \r\n");
      out.write(" \r\n");
      out.write("          <h1 class=\"guro\">Franchise in Seoul</h1>\r\n");
      out.write("          <div class=\"owl-carousel owl-theme\">\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/m1.jpg\"><img src=\"resources/main/images/m1.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/m2.jpg\"><img src=\"resources/main/images/m2.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/m3.jpg\"><img src=\"resources/main/images/m3.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/m4.jpg\"><img src=\"resources/main/images/m4.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/m5.jpg\"><img src=\"resources/main/images/m5.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/m6.jpg\"><img src=\"resources/main/images/m6.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/m7.jpg\"><img src=\"resources/main/images/m7.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <a href=\"resources/main/images/m8.jpg\"><img src=\"resources/main/images/m8.jpg\" style=\"width:300px;\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("                <!-- 식당 이미지 모달창 script  -->\r\n");
      out.write("   <script>\r\n");
      out.write("   $(function(){\r\n");
      out.write("//    이미지 클릭시 해당 이미지 모달\r\n");
      out.write("   $(\".item\").click(function(){\r\n");
      out.write("      $(\".modal1\").show();\r\n");
      out.write("      // 해당 이미지 가겨오기\r\n");
      out.write("      var imgSrc = $(this).children(\"img\").attr(\"src\");\r\n");
      out.write("      var imgAlt = $(this).children(\"img\").attr(\"alt\");\r\n");
      out.write("      $(\".modalBox1 img\").attr(\"src\", imgSrc);\r\n");
      out.write("      $(\".modalBox1 img\").attr(\"alt\", imgAlt);\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      // 해당 이미지 텍스트 가져오기\r\n");
      out.write("      var imgTit =  $(this).children(\"p\").text();\r\n");
      out.write("      $(\".modalBox1 p\").text(imgTit);\r\n");
      out.write("      \r\n");
      out.write("   // 해당 이미지에 alt값을 가져와 제목으로\r\n");
      out.write("      $(\".modalBox1 p\").text(imgAlt);\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   //.modal안에 button을 클릭하면 .modal닫기\r\n");
      out.write("   $(\".modal1 button\").click(function(){\r\n");
      out.write("      $(\".modal1\").hide();\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   //.modal밖에 클릭시 닫힘\r\n");
      out.write("   $(\".modal1\").click(function (e) {\r\n");
      out.write("    if (e.target.className != \"modal1\") {\r\n");
      out.write("      return false;\r\n");
      out.write("    } else {\r\n");
      out.write("      $(\".modal1\").hide();\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("          <script>\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("              var owl = $('.owl-carousel');\r\n");
      out.write("              owl.owlCarousel({\r\n");
      out.write("                items: 4,\r\n");
      out.write("                loop: true,\r\n");
      out.write("                margin: 10,\r\n");
      out.write("                autoplay: true,\r\n");
      out.write("                autoplayTimeout: 1000,\r\n");
      out.write("                autoplayHoverPause: true\r\n");
      out.write("              });\r\n");
      out.write("              $('.play').on('click', function() {\r\n");
      out.write("                owl.trigger('play.owl.autoplay', [1000])\r\n");
      out.write("              })\r\n");
      out.write("              $('.stop').on('click', function() {\r\n");
      out.write("                owl.trigger('stop.owl.autoplay')\r\n");
      out.write("              })\r\n");
      out.write("            })\r\n");
      out.write("          </script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"resources/assets/vendors/highlight.js\"></script>\r\n");
      out.write("    <script src=\"resources/assets/js/app.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 갤러리 이미지 carousel 적용 : https://getbootstrap.com/docs/4.6/components/carousel/ -->\r\n");
      out.write("\t\t<div class=\"gallery-box\" id=\"second\">\r\n");
      out.write("\t\t\t<h1>Popular Restaurants</h1>\r\n");
      out.write("\t\t\t<div id=\"carouselExampleCaptions\" class=\"carousel slide container\"\r\n");
      out.write("\t\t\t\tdata-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carouselExampleCaptions\" data-slide-to=\"0\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carouselExampleCaptions\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carouselExampleCaptions\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#carouselExampleCaptions\" data-slide-to=\"3\"></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"resources/main/images/res5.jpg\"><img src=\"resources/main/images/res5.jpg\" class=\"d-block w-100\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"도시1\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"resources/main/images/res2.jpg\"><img src=\"resources/main/images/res2.jpg\" class=\"d-block w-100\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"도시2\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"resources/main/images/res3.jpg\"><img src=\"resources/main/images/res3.jpg\" class=\"d-block w-100\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"도시3\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"resources/main/images/res4.png\"><img src=\"resources/main/images/res4.png\" class=\"d-block w-100\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"도시4\"></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a class=\"carousel-control-prev\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#carouselExampleCaptions\" data-slide=\"prev\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t</a> <a class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#carouselExampleCaptions\" data-slide=\"next\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- gallery-box 적용 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 기타 안내 사항 작성 -->\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div class=\"ontop2\" id=\"third\">\r\n");
      out.write("\t\t\t\t<h1>Subscription Fee</h1>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"container table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t\t\t<!-- tr>th*3 -->\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t\t<th>Plans</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Meal's Price Range</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Available Time</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Fee</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Subscribes</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Light</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Restaurants in Guro-gu\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><br>(Price ￦ 5,000 ~ ￦ 7,000)\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>12:00 ~ 13:00</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>￦ 109,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"button\" onclick=\"fn_buy1()\" class=\"btn btn-info\">결제하기</button></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Standard</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Restaurants in Guro-gu\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><br>(Price ￦ 5,000 ~ ￦ 10,000)\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>12:00 ~ 13:00</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>￦ 159,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"button\" onclick=\"fn_buy2()\" class=\"btn btn-danger\">결제하기</button></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Premium</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Restaurants in Guro-gu\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><br>(Price ￦ 5,000 ~ ￦ 15,000)\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>12:00 ~ 13:00\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>￦ 199,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"button\" onclick=\"fn_buy3()\" class=\"btn btn-primary\">결제하기</button></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 푸터 작성 -->\r\n");
      out.write("\t\t<footer class=\"card-footer\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tMATFLIX <br> 서울시 구로구 경인로 557 신한은행 4층 하이미디어컴퓨터학원 구로캠퍼스 대표전화:\r\n");
      out.write("\t\t\t\t\t\t\t02-3667-0008 <br> COPYRIGHT &copy; by Matflix. ALL RIGHTS\r\n");
      out.write("\t\t\t\t\t\t\tRESERVED\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- top 버튼 -->\r\n");
      out.write("\t\t<button type=\"button\" style=\"position: fixed; left: 20px; bottom: 20px; border: none; background: none;\">\r\n");
      out.write("\t\t\t<a href=\"#top\" class=\"btn btn-outline-secondary\"><img src=\"resources/main/images/airplane-fill.svg\" /></a>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- wrapper 적용 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- tubular 적용 -->\r\n");
      out.write("\t<script src=\"resources/main/javascript/jquery.tubular.1.0.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('document').ready(function() {\r\n");
      out.write("\t\t\tvar options = {\r\n");
      out.write("\t\t\t\tvideoId : 'F3zw1Gvn4Mk',\r\n");
      out.write("\t\t\t\t// mute는 동영상 실행 시 음소거 설정 기능입니다!\r\n");
      out.write("\t\t\t\tmute : true\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t$('#wrapper').tubular(options);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t(function() {\r\n");
      out.write("\t\t\tvar w = window;\r\n");
      out.write("\t\t\tif (w.ChannelIO) {\r\n");
      out.write("\t\t\t\treturn w.console.error(\"ChannelIO script included twice.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar ch = function() {\r\n");
      out.write("\t\t\t\tch.c(arguments);\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tch.q = [];\r\n");
      out.write("\t\t\tch.c = function(args) {\r\n");
      out.write("\t\t\t\tch.q.push(args);\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tw.ChannelIO = ch;\r\n");
      out.write("\t\t\tfunction l() {\r\n");
      out.write("\t\t\t\tif (w.ChannelIOInitialized) {\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tw.ChannelIOInitialized = true;\r\n");
      out.write("\t\t\t\tvar s = document.createElement(\"script\");\r\n");
      out.write("\t\t\t\ts.type = \"text/javascript\";\r\n");
      out.write("\t\t\t\ts.async = true;\r\n");
      out.write("\t\t\t\ts.src = \"https://cdn.channel.io/plugin/ch-plugin-web.js\";\r\n");
      out.write("\t\t\t\tvar x = document.getElementsByTagName(\"script\")[0];\r\n");
      out.write("\t\t\t\tif (x.parentNode) {\r\n");
      out.write("\t\t\t\t\tx.parentNode.insertBefore(s, x);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (document.readyState === \"complete\") {\r\n");
      out.write("\t\t\t\tl();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tw.addEventListener(\"DOMContentLoaded\", l);\r\n");
      out.write("\t\t\t\tw.addEventListener(\"load\", l);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})();\r\n");
      out.write("\r\n");
      out.write("\t\tChannelIO('boot', {\r\n");
      out.write("\t\t\t\"pluginKey\" : \"929c67b4-ec76-4082-9b38-6f8e7dfc9066\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
