/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2023-06-15 00:24:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class membership_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Disfruta de Netflix, películas y series en streaming en tu smart TV, consola, PC, Mac, móvil, tableta y más dispositivos.\" />\r\n");
      out.write("<title>MATFLIX</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"resources/img/mlogo.svg\"\">\r\n");
      out.write("<link href=\"resources/membership/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"canonical\"\r\n");
      out.write("\thref=\"https://getbootstrap.com/docs/4.5/examples/floating-labels/\">\r\n");
      out.write("<link href=\"../assets/dist/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"floating-labels.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"resources/membership/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<main class=\"container-fluid\">\r\n");
      out.write("\t\t<!---->\r\n");
      out.write("\t\t<section id=\"backGround\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid relative\">\r\n");
      out.write("\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t<a href=\"/main.jsp\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"resources/membership/img/matlogos.svg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Responsive image LOGO\" class=\"img-fluid\" /></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"/customLogin\"><button type=\"button\" class=\"btn btn-danger\">로그인</button></a>\r\n");
      out.write("\t\t\t\t</header>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"jumbotron jumbotron-fluid relative mt-5\">\r\n");
      out.write("\t\t\t\t<h1>이젠 맛있는 음식을 구독제로</h1>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<p class=\"lead\">다양한 음식점에서 드세요. 언제든 해지하실 수 있습니다.</p>\r\n");
      out.write("\t\t\t\t<form method=\"POST\" action=\"/action_page.php\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-signin needs-validation\" novalidate>\r\n");
      out.write("\t\t\t\t\t<div class=\"row no-gutters justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 first\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>드실 준비가 되셨나요? 멤버십을 등록하거나 재시작하려면 이메일 주소를 입력하세요.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 col-lg-9 second form-label-group my-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" id=\"inputEmail\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Correo electrónico\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpattern=\"[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$\" maxlength=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\t\tminlength=\"5\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"valid-feedback\">다음 단계로 이동합니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">이메일 주소를 넣어주세요.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputEmail\">이메일 주소</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 col-lg-3 third my-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/signup.jsp\"><button class=\"suscribe\">\r\n");
      out.write("\t\t\t\t\t\t\t\t시작하기<i class=\"arrow right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h3>자주 묻는 질문</h3>\r\n");
      out.write("\t\t\t\t<div id=\"accordion\" class=\"mb-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\" id=\"headingOne\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#collapseOne\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-controls=\"collapseOne\">\r\n");
      out.write("\t\t\t\t\t\t\t\t맛플릭스란 무엇인가요?\r\n");
      out.write("\t\t\t\t\t\t\t\t<svg viewBox=\"0 0 26 26\" class=\"svg-icon svg-closed rotated\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfocusable=\"true\">\r\n");
      out.write("                    <path\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\td=\"M10.5 9.3L1.8 0.5 0.5 1.8 9.3 10.5 0.5 19.3 1.8 20.5 10.5 11.8 19.3 20.5 20.5 19.3 11.8 10.5 20.5 1.8 19.3 0.5 10.5 9.3Z\"></path>\r\n");
      out.write("                  </svg>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"collapseOne\" class=\"collapse show\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"headingOne\" data-parent=\"#accordion\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">맛플릭스는 각종 수상 경력에 빛나는 레스토랑의 다양한 음식을 드실수 있는 구독 서비스입니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t점심식사를 합리적인 가격으로 다양하게 즐길 수 있습니다. </div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\" id=\"headingTwo\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#collapseTwo\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-controls=\"collapseTwo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t맛플릭스에서 어떤 음식을 먹을 수 있나요?\r\n");
      out.write("\t\t\t\t\t\t\t\t<svg viewBox=\"0 0 26 26\" class=\"svg-icon svg-closed rotated\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfocusable=\"true\">\r\n");
      out.write("                    <path\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\td=\"M10.5 9.3L1.8 0.5 0.5 1.8 9.3 10.5 0.5 19.3 1.8 20.5 10.5 11.8 19.3 20.5 20.5 19.3 11.8 10.5 20.5 1.8 19.3 0.5 10.5 9.3Z\"></path>\r\n");
      out.write("                  </svg>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"collapseTwo\" class=\"collapse show\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"headingTwo\" data-parent=\"#accordion\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">맛플릭스는 한식, 중식, 일식, 양식 등 수많은 레스토랑을 확보하고 있습니다. </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\" id=\"headingThree\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#collapseThree\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-controls=\"collapseThree\">\r\n");
      out.write("\t\t\t\t\t\t\t\t맛플릭스 요금은 얼마인가요?\r\n");
      out.write("\t\t\t\t\t\t\t\t<svg viewBox=\"0 0 26 26\" class=\"svg-icon svg-closed rotated\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfocusable=\"true\">\r\n");
      out.write("                    <path\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\td=\"M10.5 9.3L1.8 0.5 0.5 1.8 9.3 10.5 0.5 19.3 1.8 20.5 10.5 11.8 19.3 20.5 20.5 19.3 11.8 10.5 20.5 1.8 19.3 0.5 10.5 9.3Z\"></path>\r\n");
      out.write("                  </svg>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"collapseThree\" class=\"collapse show\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"headingThree\" data-parent=\"#accordion\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">맛플릭스의 월간 구독요금은 메인페이지에서 보실 수 있습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\" id=\"headingFour\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#collapseFour\" aria-expanded=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-controls=\"collapseFour\">\r\n");
      out.write("\t\t\t\t\t\t\t\t어디서 먹을 수 있나요?\r\n");
      out.write("\t\t\t\t\t\t\t\t<svg viewBox=\"0 0 26 26\" class=\"svg-icon svg-closed rotated\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfocusable=\"true\">\r\n");
      out.write("                    <path\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\td=\"M10.5 9.3L1.8 0.5 0.5 1.8 9.3 10.5 0.5 19.3 1.8 20.5 10.5 11.8 19.3 20.5 20.5 19.3 11.8 10.5 20.5 1.8 19.3 0.5 10.5 9.3Z\"></path>\r\n");
      out.write("                  </svg>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"collapseFour\" class=\"collapse show\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"headingFour\" data-parent=\"#accordion\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">맛플릭스와 제휴한 가맹점에서 드실 수 있습니다. 추후 해외 레스토랑과도 제휴할 계획입니다.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\" id=\"headingFive\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#collapseFive\" aria-expanded=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-controls=\"collapseFive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t멤버쉽을 해지하려면 어떻게 하나요?\r\n");
      out.write("\t\t\t\t\t\t\t\t<svg viewBox=\"0 0 26 26\" class=\"svg-icon svg-closed rotated\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfocusable=\"true\">\r\n");
      out.write("                    <path\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\td=\"M10.5 9.3L1.8 0.5 0.5 1.8 9.3 10.5 0.5 19.3 1.8 20.5 10.5 11.8 19.3 20.5 20.5 19.3 11.8 10.5 20.5 1.8 19.3 0.5 10.5 9.3Z\"></path>\r\n");
      out.write("                  </svg>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"collapseFive\" class=\"collapse show\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"headingFive\" data-parent=\"#accordion\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">맛플릭스는 해지가 간편합니다. 성가신 계약도, 약정도\r\n");
      out.write("\t\t\t\t\t\t\t\t없으니까요. 멤버십 해지도 온라인에서 클릭 두 번이면 완료할 수 있습니다. 해지 수수료도 없으니 원할 때 언제든\r\n");
      out.write("\t\t\t\t\t\t\t\t계정을 시작하거나 종료하세요.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<form method=\"POST\" action=\"/action_page.php\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-signin needs-validation\" novalidate>\r\n");
      out.write("\t\t\t\t\t<div class=\"row no-gutters justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 first\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>드실 준비가 되셨나요? 멤버십을 등록하거나 재시작하려면 이메일 주소를 입력하세요.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 col-lg-9 second form-label-group my-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" id=\"inEmail\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Correo electrónico\"\r\n");
      out.write("\t\t\t\t\t\t\t\tpattern=\"[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$\" maxlength=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\t\tminlength=\"5\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"valid-feedback\">다음 단계로 이동합니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">이메일 주소를 넣어주세요.</div>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inEmail\">이메일 주소</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12 col-lg-3 third my-4\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/signup.jsp\"><button class=\"suscribe\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t시작하기<i class=\"arrow right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</main>\r\n");
      out.write("\t<!---footer---------->\r\n");
      out.write("\t<footer class=\"page-footer font-small blue text-muted\">\r\n");
      out.write("\t\t<div class=\"container text-left\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-space-between\">\r\n");
      out.write("\t\t\t\t<div class=\"col-12 mt-5 mb-2\">\r\n");
      out.write("\t\t\t\t\t<p class=\"h5 text-capitalize\">질문이 있으신가요? 문의 전화: 하이미디어컴퓨터학원\r\n");
      out.write("\t\t\t\t\t\t구로캠퍼스(02-3667-0008)</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr class=\"clearfix w-100 d-md-none pb-3\" />\r\n");
      out.write("\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled articles mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/map.jsp\">찾아 오시는 길</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">입사 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled articles mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">이용 약관</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled articles mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">계정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">개인정보 처리방침</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled articles mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">투자 정보(IR)</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">법적 고지</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t<button class=\"btn language dropdown-toggle text-left\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tid=\"dropdownMenuButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t<span class=\"globe\"> &#127770;</span>한국어\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">한국어</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">English</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p class=\"footer-copyright pt-5 pb-2 font-weight-lighter text-muted\">\r\n");
      out.write("\t\t\t\t맛플릭스 코리아</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"resources/membership/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/membership/js/main.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t* {\r\n");
      out.write("\t\t\tmargin: 0;\r\n");
      out.write("\t\t\tpadding: 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t\tfont-size: 12px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tinput {\r\n");
      out.write("\t\t\tvertical-align: middle;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t#notice_wrap {\r\n");
      out.write("\t\t\twidth: 400px;\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tright: 100px;\r\n");
      out.write("\t\t\ttop: 110px;\r\n");
      out.write("\t\t\tbox-shadow: 0 0 0 #fff;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t.closeWrap {\r\n");
      out.write("\t\t\tbackground-color: #000;\r\n");
      out.write("\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\ttext-align: right;\r\n");
      out.write("\t\t\tpadding: 5px 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t.closeWrap button {\r\n");
      out.write("\t\t\tmargin-left: 20px;\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script src=\"resources/popup/js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"resources/popup/js/jquery.cookie.js\"></script>\r\n");
      out.write("\t<!-- https://cdnjs.com/libraries/jquery-cookie -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// jquery-cookie 플러그인을 사용하면 간편하게 쿠키(cookie)를 생성하고\r\n");
      out.write("\t\t// 쿠키 만료일을 설정할 수 있습니다. 쿠키란 '사이트를 방문한 사용자의\r\n");
      out.write("\t\t// 소량(4kb이하) 브라우저 정보를 저장할 수 있는 공간'을 말합니다.\r\n");
      out.write("\t\t// 쿠키는 하나의 도메인당 최대 20개를 생성할 수 있고,\r\n");
      out.write("\t\t// 최대 4kb까지 저장할 수 있습니다.\r\n");
      out.write("\t\t$(function () {\r\n");
      out.write("\t\t\t// 쿠키(\"popup\")의 값이 \"none\"이면 id값이 \"notice_wrap\" 인 요소를 숨깁니다.\r\n");
      out.write("\t\t\tif ($.cookie(\"popup\") == \"none\") {\r\n");
      out.write("\t\t\t\t$(\"#notice_wrap\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// class값이 \"closeBtn\"인 요소를 클릭하면 체크박스의 체크 유무에 따라 쿠키를 생성하여 3일간만 저장합니다.\r\n");
      out.write("\t\t\tvar $expiresChk = $(\"#expiresChk\");\r\n");
      out.write("\t\t\t$(\".closeBtn\").on(\"click\", closePop);\r\n");
      out.write("\t\t\tfunction closePop() {\r\n");
      out.write("\t\t\t\tif ($expiresChk.is(\":checked\")) {\r\n");
      out.write("\t\t\t\t\t$.cookie(\"popup\", \"none\", { expires: 3, path: \"/\" });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#notice_wrap\").fadeOut(\"fast\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"notice_wrap\">\r\n");
      out.write("\t\t<img src=\"resources/membership/img/mem_event.jpg\" alt=\"공지사항\" style=\"width:400px\";>\r\n");
      out.write("\t\t<p class=\"closeWrap\">\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"expiresChk\" id=\"expiresChk\">\r\n");
      out.write("\t\t\t<label for=\"expiresChk\">3일 동안 이 창 열지않기</label>\r\n");
      out.write("\t\t\t<button class=\"closeBtn\">닫기</button>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
