/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2023-06-10 08:13:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>MyPage</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/mypage/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/mypage/css/mystyle.css\">\r\n");
      out.write("    <script src=\"resources/mypage/javascript/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/mypage/javascript/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"resources/mypage/images/mlogo.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/mypage/css/mypage.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"top\"></div>\t\t\r\n");
      out.write("\t<!-- sticky-top 적용 : https://getbootstrap.com/docs/4.0/utilities/position/ -->\r\n");
      out.write("\t<div class=\"mybox sticky-top\">\r\n");
      out.write("\t\t<!-- 네비게이션 바 navbar-example2 활용 : https://getbootstrap.com/docs/4.0/components/scrollspy/#one -->\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light container\">\r\n");
      out.write("\t\t\t<!-- 로고 작성 -->\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"main.jsp\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"resources/mypage/images/mlogo.svg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<!-- https://getbootstrap.com/docs/4.0/components/navbar/ -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t</nav>    \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"account\">\r\n");
      out.write("    <h1>계정</h1><hr>\r\n");
      out.write("    <div class=\"section1\">\r\n");
      out.write("        멤버십 & 결제 정보 <br>\r\n");
      out.write("        <button>멤버십 해지</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"section2\">\r\n");
      out.write("        사용자 이메일 <br>\r\n");
      out.write("        비밀번호 <br>\r\n");
      out.write("        전화번호 <br> <hr>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section3\">\r\n");
      out.write("\t\t<a href=\"#\">이메일 주소 변경</a> <br>\r\n");
      out.write("\t\t<a href=\"#\">비밀번호 변경 </a> <br>\r\n");
      out.write("\t\t<a href=\"#\">휴대폰 번호 변경 </a> <hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section1\">\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"section2\">\r\n");
      out.write("      <br>\r\n");
      out.write("\t  <br>\r\n");
      out.write("\t  <br>\r\n");
      out.write("\t  <hr>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section3\">\r\n");
      out.write("\t\t<a href=\"#\">결제 정보 관리</a> <br>\r\n");
      out.write("\t\t<a href=\"#\">결제 상세 정보</a> <br>\r\n");
      out.write("\t\t<a href=\"#\">결제일 변경</a> <hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section1\">\r\n");
      out.write("\t\t멤버십 상세 정보<hr> <br> \r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"section2\">\r\n");
      out.write("\t구독한 멤버십 <hr>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"section3\">\r\n");
      out.write("\t  <a href=\"#\">멤버십 변경</a> <br> <hr>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section1\">\r\n");
      out.write("\t\t보안 & 개인 정보<br> \r\n");
      out.write("  \t</div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"section2\">\r\n");
      out.write("\t이 계정에 대한 접근 권한을 관리하세요\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"section3\">\r\n");
      out.write("\t  <a href=\"#\">개인 정보 다운로드</a> <br> \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>   \r\n");
      out.write("\r\n");
      out.write("<!-- footer start -->\r\n");
      out.write("    <footer class=\"page-footer font-small blue text-muted\">\r\n");
      out.write("\t\t<div class=\"container text-left\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-space-between\">\r\n");
      out.write("\t\t\t\t<div class=\"col-12 mt-5 mb-2\">\r\n");
      out.write("\t\t\t\t\t<p class=\"h5 text-capitalize\">질문이 있으신가요? 문의 전화: 하이미디어컴퓨터학원\r\n");
      out.write("\t\t\t\t\t\t구로캠퍼스(02-3667-0008)</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr class=\"clearfix w-100 d-md-none pb-3\" />\r\n");
      out.write("\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled articles mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">찾아 오시는 길</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">입사 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled articles mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">이용 약관</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled articles mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">계정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">개인정보 처리방침</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled articles mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">투자 정보(IR)</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">법적 고지</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t<button class=\"btn language dropdown-toggle text-left\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tid=\"dropdownMenuButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t<span class=\"globe\"> &#127770;</span>한국어\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">한국어</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">English</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p class=\"footer-copyright pt-5 pb-2 font-weight-lighter text-muted\">\r\n");
      out.write("\t\t\t\t맛플릭스 코리아</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
